/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CmsPreviewRouteImport } from './routes/cms-preview'
import { Route as MemosRouteImport } from './routes/memos'
import { Route as WorksRouteImport } from './routes/works'
import { Route as BlogsBlogIdRouteImport } from './routes/blogs_.$blogId'
import { Route as MemosMemoIdRouteImport } from './routes/memos_.$memoId'
import { Route as WorksWorkIdRouteImport } from './routes/works_.$workId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsPreviewRoute = CmsPreviewRouteImport.update({
  id: '/cms-preview',
  path: '/cms-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosRoute = MemosRouteImport.update({
  id: '/memos',
  path: '/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdRoute = BlogsBlogIdRouteImport.update({
  id: '/blogs_/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosMemoIdRoute = MemosMemoIdRouteImport.update({
  id: '/memos_/$memoId',
  path: '/memos/$memoId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works_/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/cms-preview': typeof CmsPreviewRoute
  '/memos': typeof MemosRoute
  '/works': typeof WorksRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/cms-preview': typeof CmsPreviewRoute
  '/memos': typeof MemosRoute
  '/works': typeof WorksRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/cms-preview': typeof CmsPreviewRoute
  '/memos': typeof MemosRoute
  '/works': typeof WorksRoute
  '/blogs_/$blogId': typeof BlogsBlogIdRoute
  '/memos_/$memoId': typeof MemosMemoIdRoute
  '/works_/$workId': typeof WorksWorkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/cms-preview'
    | '/memos'
    | '/works'
    | '/blogs/$blogId'
    | '/memos/$memoId'
    | '/works/$workId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/cms-preview'
    | '/memos'
    | '/works'
    | '/blogs/$blogId'
    | '/memos/$memoId'
    | '/works/$workId'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/cms-preview'
    | '/memos'
    | '/works'
    | '/blogs_/$blogId'
    | '/memos_/$memoId'
    | '/works_/$workId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRoute
  CmsPreviewRoute: typeof CmsPreviewRoute
  MemosRoute: typeof MemosRoute
  WorksRoute: typeof WorksRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  MemosMemoIdRoute: typeof MemosMemoIdRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms-preview': {
      id: '/cms-preview'
      path: '/cms-preview'
      fullPath: '/cms-preview'
      preLoaderRoute: typeof CmsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos': {
      id: '/memos'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs_/$blogId': {
      id: '/blogs_/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos_/$memoId': {
      id: '/memos_/$memoId'
      path: '/memos/$memoId'
      fullPath: '/memos/$memoId'
      preLoaderRoute: typeof MemosMemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works_/$workId': {
      id: '/works_/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRoute,
  CmsPreviewRoute: CmsPreviewRoute,
  MemosRoute: MemosRoute,
  WorksRoute: WorksRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  MemosMemoIdRoute: MemosMemoIdRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
